package exception;

public class Try {
	
	public static void main(String[] args)
	
	{
		int result,a,b;
		
		int a1=10;
		int b1=0;
		
		try {
		    result  = a1 / b1;
		    System.out.println("Result = " + result);
		  }
		 
		  // catch block
		 
		  catch (ArithmeticException e) {
		    System.out.println("Exception caught: Division by zero.");
		  }

}

}